[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
decorations = "None"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

# [colors.primary]
# background = "#282828"
